# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: captcha.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'captcha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcaptcha.proto\x12\x07\x63\x61ptcha\"E\n\x0cSolveRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12(\n\nforce_type\x18\x02 \x01(\x0e\x32\x14.captcha.CaptchaType\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\xa5\x01\n\rSolveResponse\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.captcha.CaptchaType\x12\x0e\n\x06solved\x18\x02 \x01(\x08\x12\r\n\x05token\x18\x03 \x01(\t\x12(\n\x0b\x63oordinates\x18\x04 \x03(\x0b\x32\x13.captcha.Coordinate\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x01\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"\x10\n\x0eHealthzRequest\"!\n\x0fHealthzResponse\x12\x0e\n\x06status\x18\x01 \x01(\t*w\n\x0b\x43\x61ptchaType\x12\x1c\n\x18\x43\x41PTCHA_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43\x41PTCHA_TYPE_NONE\x10\x01\x12\x16\n\x12\x43\x41PTCHA_TYPE_CLICK\x10\x02\x12\x1b\n\x17\x43\x41PTCHA_TYPE_COORDINATE\x10\x03\x32\x85\x01\n\rCaptchaSolver\x12\x36\n\x05Solve\x12\x15.captcha.SolveRequest\x1a\x16.captcha.SolveResponse\x12<\n\x07Healthz\x12\x17.captcha.HealthzRequest\x1a\x18.captcha.HealthzResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'captcha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPTCHATYPE']._serialized_start=354
  _globals['_CAPTCHATYPE']._serialized_end=473
  _globals['_SOLVEREQUEST']._serialized_start=26
  _globals['_SOLVEREQUEST']._serialized_end=95
  _globals['_COORDINATE']._serialized_start=97
  _globals['_COORDINATE']._serialized_end=131
  _globals['_SOLVERESPONSE']._serialized_start=134
  _globals['_SOLVERESPONSE']._serialized_end=299
  _globals['_HEALTHZREQUEST']._serialized_start=301
  _globals['_HEALTHZREQUEST']._serialized_end=317
  _globals['_HEALTHZRESPONSE']._serialized_start=319
  _globals['_HEALTHZRESPONSE']._serialized_end=352
  _globals['_CAPTCHASOLVER']._serialized_start=476
  _globals['_CAPTCHASOLVER']._serialized_end=609
# @@protoc_insertion_point(module_scope)
